#!/usr/bin/python

import os, sys

os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'

from djmail.models import User
from django.conf import settings

user = User.objects.get(pk = int(sys.argv[1]))

try:
    os.system('mkdir -p %s/%s/%s' % (settings.MAILDIR, user.domain.name, user.username))
except OSError:
    pass

os.system('maildirmake /%s/%s/%s/.maildir' % (settings.MAILDIR, user.domain.name, user.username))
